#!/bin/bash
set -x
ssh_test="ssh -q -o BatchMode=yes -o StrictHostKeyChecking=no -o ConnectTimeout=5"
yc compute instance create --name servr --hostname server \
--zone ru-central1-d \
--network-interface subnet-name=default-ru-central1-d,nat-ip-version=ipv4 \
--create-boot-disk image-folder-id=standard-images,image-family=ubuntu-24-04-lts \
--metadata-from-file user-data=/home/serg/project_vpn/metadata-server > ~/project_vpn/server.inf
serv=$(grep -A1 one_to server.inf | grep address | awk '{print $2}')
$ssh_test $serv exit 0
while [ $? != 0 ]; do sleep 30;$ssh_test $serv exit 0 ;done
sleep 90 
ssh -t $serv 'cd /home/serg/server-set/openvpn_exporter-0.3.0 &&\
       sudo bash -c "go build -o /usr/local/bin/openvpn_exporter main.go"\
       && sleep 10 && sudo systemctl daemon-reload &&\
       sudo systemctl enable openvpn_exporter.service &&\
       sudo systemctl start openvpn_exporter.service &&\
       systemctl status openvpn_exporter.service prometheus-node-exporter'       
exit 0
